MvcOnlineTicariOtomasyon/Controllers/SatisController.cs
using MvcOnlineTicariOtomasyon.Models.Siniflar;
using MvcOnlineTicariOtomasyon.Models.Siniflar.Context;
using PagedList;
using System;
using System.Collections.Generic;
using System.Linq;

using System.Web;
using System.Web.Mvc;

namespace MvcOnlineTicariOtomasyon.Controllers
{
    [Authorize(Roles = "A")]
    public class SatisController : Controller
    {
        // GET: Satis
        Context c = new Context();
        public ActionResult Index(string p, int sayfa = 1)
        {
            var satislar = from x in c.SatisHarekets.OrderByDescending(x=>x.SatisId) select x;
            if (!string.IsNullOrEmpty(p))
            {
                satislar = satislar.Where(y => y.Cari.CariSoyad.Contains(p));
            }
            return View(satislar.ToList().ToPagedList(sayfa, 12));

            //var satisListesi = c.SatisHarekets.OrderBy(x=>x.Durum).ToList();
            //return View(satisListesi);
        }
       
        
        
        [HttpGet]
        public ActionResult YeniSatis()
        {
            DropdownDoldur();

            return View();
        }

        private void DropdownDoldur()
        {
            List<SelectListItem> deger1 = (from x in c.Uruns.OrderBy(x => x.UrunAd).ToList()//droplistdown dolduruyoruz
                                           select new SelectListItem
                                           {
                                               Text = x.UrunAd,
                                               Value = x.UrunId.ToString()
                                           }).ToList();


            List<SelectListItem> deger2 = (from x in c.Caris.OrderBy(x => x.CariAd).ToList()//droplistdown dolduruyoruz
                                           select new SelectListItem
                                           {
                                               Text = x.CariAd + " " + x.CariSoyad,
                                               Value = x.CariId.ToString()
                                           }).ToList();
            List<SelectListItem> deger3 = (from x in c.Personels.Where(x => x.DepartmanId == 1 || x.DepartmanId == 2).ToList()//droplistdown dolduruyoruz
                                           select new SelectListItem
                                           {
                                               Text = x.PersonelAd + " " + x.PersonelSoyad,
                                               Value = x.PersonelId.ToString()
                                           }).ToList();
            ViewBag.dgr1 = deger1;
            ViewBag.dgr2 = deger2;
            ViewBag.dgr3 = deger3;
        }


        [HttpPost]
        public ActionResult YeniSatis(SatisHareket satisHareket)
        {
            satisHareket.Durum = false;
            satisHareket.KargoDurum = false;
            satisHareket.Tarih = DateTime.Parse(DateTime.Now.ToShortDateString());
            c.SatisHarekets.Add(satisHareket);
            c.SaveChanges();
            return RedirectToAction("Index");
        }

        
        public ActionResult SatisGetir(int id)
        {
            DropdownDoldur();
            var satisDoldur = c.SatisHarekets.Find(id);
            return View("SatisGetir", satisDoldur);
        }
        
        [HttpPost]
        public ActionResult SatisGuncelle(SatisHareket satisHareket)
        {
            var satisUpdate = c.SatisHarekets.Find(satisHareket.SatisId);
            satisUpdate.UrunId = satisHareket.UrunId;
            satisUpdate.CariId = satisHareket.CariId;
            satisUpdate.PersonelId = satisHareket.PersonelId;
            satisUpdate.Adet = satisHareket.Adet;
            satisUpdate.Fiyat = satisHareket.Fiyat;
            satisUpdate.ToplamTutar = satisHareket.ToplamTutar;
            satisUpdate.Tarih = DateTime.Parse(DateTime.Now.ToShortDateString()); ;

            c.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult SatisDetay(int id)
        {
            var satisDetay = c.SatisHarekets.Where(x => x.SatisId == id).ToList();
            return View(satisDetay);
        }

      
    }
}

MvcOnlineTicariOtomasyon/Views/Satis/Index.cshtml
@using MvcOnlineTicariOtomasyon.Models.Siniflar
@using PagedList;
@using PagedList.Mvc;
@model PagedList.IPagedList<SatisHareket>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<br />
@*<a href="/Satis/YeniSatis" class="btn btn-primary">Satiş Yap</a>*@
@using (Html.BeginForm("Index", "Satis", FormMethod.Get))
{
    <p>
        Soyadı Giriniz: @Html.TextBox("p")
        <input type="submit" value="Ara" />
    </p>
}
<table id="tbl1" class="table table-striped" style="margin-top:20px">
    <thead>
        <tr>

            <th>Ürün</th>
            <th>Cari</th>

            <th>Adet</th>
            <th>Fiyat</th>
            <th>Toplam</th>
            <th>Tarih</th>
            <th>Güncelle</th>
            <th>Detaylar</th>
            <th>Fatura Durumu</th>
            <th>Kargola</th>
        </tr>
    </thead>
    @foreach (var k in Model)
    {
        <tr>

            <td>@k.Urun.UrunAd</td>
            <td>@k.Cari.CariAd @k.Cari.CariSoyad</td>

            <td>@k.Adet</td>
            <td>@k.Fiyat ₺</td>
            <td>@k.ToplamTutar ₺</td>
            <td>@k.Tarih.ToShortDateString()</td>
            <td><a href="/Satis/SatisGetir/@k.SatisId" class="btn btn-warning">Güncelle</a></td>
            <td><a href="/Satis/SatisDetay/@k.SatisId" class="btn btn-default" style="background-color:lightcoral; color:white">Detaylar</a></td>

            @if (k.Durum)
            {
                <td><a href="" class="btn btn-success">Fatura Var</a></td>
                if (k.KargoDurum)
                {
                    <td><a href="" class="btn btn-success">Kargolandı </a></td>
                }
                else
                {
                    <td><a href="/Kargo/KargoEkle/@k.SatisId" class="btn btn-primary">Kargoya ver</a></td>
                }


            }
            else
            {
                <td><a href="/FaturaSatis/FaturaEkle/@k.SatisId" class="btn btn-danger">Fatura Kes</a></td>
            }
        </tr>
    }
</table>
@Html.PagedListPager((IPagedList)Model, sayfa => Url.Action("Index", new { sayfa }))
@*<a href="/Satis/YeniSatis" class="btn btn-info">Yeni Satış Yap</a>*@

@*<link href="~/Content/bootstrap.css" rel="stylesheet" />*@

<script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>




<link href="https://cdn.datatables.net/1.10.15/css/dataTables.bootstrap.min.css" rel="stylesheet" />
<link href="https://cdn.datatables.net/responsive/2.1.1/css/responsive.bootstrap.min.css" rel="stylesheet" />
<script src="https://cdn.datatables.net/1.10.15/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/1.10.15/js/dataTables.bootstrap4.min.js "></script>

<script>
    $('#tbl1').dataTable({});
</script>

@*<table class="table table-striped " style="margin-top:20px;">
        <tr>
            <th>ID</th>
            <th>Ürün</th>
            <th>Cari</th>
            <th>Personel</th>
            <th>Adet</th>
            <th>Fiyat</th>
            <th>Toplam</th>
            <th>Tarih</th>

            <th>Güncelle</th>
            <th>Detaylar</th>

        </tr>
        @foreach (var d in Model)
        {
            <tr>
                <td>@d.SatisId</td>
                <td>@d.Urun.UrunAd</td>
                <td>@d.Cari.CariAd @d.Cari.CariSoyad</td>
                <td>@d.Personel.PersonelAd @d.Personel.PersonelSoyad</td>
                <td>@d.Adet</td>
                <td>@d.Fiyat</td>
                <td>@d.ToplamTutar</td>
                <td>@d.Tarih.ToShortDateString()</td>

                <td><a href="/Satis/SatisGetir/@d.SatisId" class="btn btn-warning">Güncelle</a></td>
                <td><a href="/Satis/SatisDetay/@d.SatisId" class="btn btn-info">Satış Geçmişi</a></td>

            </tr>
        }

    </table>*@

MvcOnlineTicariOtomasyon/Views/Satis/SatisDetay.cshtml
@using MvcOnlineTicariOtomasyon.Models.Siniflar
@model List<SatisHareket>

@{
    ViewBag.Title = "SatisDetay";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<br />
<h2> Satış Detayı</h2>
<br />

<table class="table table-striped">
        <tr>
            <th>Satış Id</th>
            <th>Ürün</th>
            <th>Cari</th>
            <th>Personel</th>
            <th>Fiyat</th>
            <th>Adet</th>
            <th>Toplam</th>
            <th>Tarih</th>


        </tr>

        @foreach (var s in Model)
        {

            <tr>
                <td>@s.SatisId</td>
                <td>@s.Urun.UrunAd</td>
                <td>@s.Cari.CariAd @s.Cari.CariSoyad </td>
                <td>@s.Personel.PersonelAd @s.Personel.PersonelSoyad </td>
                <td>@s.Fiyat</td>
                <td>@s.Adet</td>
                <td>@s.ToplamTutar</td>
                <td>@s.Tarih.ToShortDateString()</td>



            </tr>
        }

    </table>
    <br />
    <hr />


    <button href="#" class="btn btn-primary">Yazdır</button>

MvcOnlineTicariOtomasyon/Views/Satis/SatisGetir.cshtml
@model MvcOnlineTicariOtomasyon.Models.Siniflar.SatisHareket
@{
    ViewBag.Title = "SatisGetir";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<br />
<h2>Satiş Güncelleme</h2>
<br />

@using (Html.BeginForm("SatisGuncelle", "Satis", FormMethod.Post))
{
    <div class="form-group">

        @Html.HiddenFor(x => x.SatisId)
        @Html.Label("Ürün")
        @Html.DropDownListFor(x => x.UrunId, (List<SelectListItem>)ViewBag.dgr1, new { @class = "form-control" })
        <br />
        @Html.Label("Cari ")
        @Html.DropDownListFor(x => x.CariId, (List<SelectListItem>)ViewBag.dgr2, new { @class = "form-control" })
        <br />
        @Html.Label("Personel ")
        @Html.DropDownListFor(x => x.PersonelId, (List<SelectListItem>)ViewBag.dgr3, new { @class = "form-control" })
        <br />
        @Html.Label("Adet ")
        @Html.TextBoxFor(x => x.Adet, new { @class = "form-control" })
        <br />
        @Html.Label("Fiyat ")
        @Html.TextBoxFor(x => x.Fiyat, new { @class = "form-control" })
        <br />
        @Html.Label("Toplam ")

        @Html.TextBoxFor(x => x.ToplamTutar, new { @class = "form-control" })

        <br />
        @Html.Label("Tarih ")

        @Html.TextBoxFor(x => x.Tarih, new { @class = "form-control" })

        <br />
        <button class="btn btn-warning">Güncelle</button>
    </div>
}

MvcOnlineTicariOtomasyon/Views/Satis/YeniSatis.cshtml
@model MvcOnlineTicariOtomasyon.Models.Siniflar.SatisHareket
@{
    ViewBag.Title = "YeniSatis";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<br />
<h2>Yeni Satış Sayfası</h2>
<br />
<form class="form-group" method="post">
    @Html.Label("Ürün ")
    @Html.DropDownListFor(x => x.UrunId, (List<SelectListItem>)ViewBag.dgr1, new { @class = "form-control" })
    <br />
    @Html.Label("Cari ")
    @Html.DropDownListFor(x => x.CariId, (List<SelectListItem>)ViewBag.dgr2, new { @class = "form-control" })
    <br />
    @Html.Label("Personel ")
    @Html.DropDownListFor(x => x.PersonelId, (List<SelectListItem>)ViewBag.dgr3, new { @class = "form-control" })
    <br />
    @Html.Label("Adet ")
    @Html.TextBoxFor(x => x.Adet, new { @class = "form-control" })
    <br />
    @Html.Label("Fiyat ")
    @Html.TextBoxFor(x => x.Fiyat, new { @class = "form-control" })
    <br />
    
    
    @Html.Label("Toplam ")
    @Html.TextBoxFor(x => x.ToplamTutar, new { @class = "form-control" })
    <br />
    <button class="btn btn-danger">Satış Yap</button>
</form>