MvcOnlineTicariOtomasyon/Controllers/KargoController.cs
using MvcOnlineTicariOtomasyon.Models.Siniflar;
using MvcOnlineTicariOtomasyon.Models.Siniflar.Context;
using System;
using PagedList;
using PagedList.Mvc;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.IO;
using QRCoder;
using System.Drawing;
using System.Drawing.Imaging;

namespace MvcOnlineTicariOtomasyon.Controllers
{
    [Authorize(Roles = "A,U")]
    public class KargoController : Controller
    {
        // GET: Kargo

        Context c = new Context();
        public ActionResult Index(string p, int sayfa = 1)
        {
            var mail = (string)Session["Mail"];
            var personel = c.Personels.Where(x => x.MAil == mail).FirstOrDefault();
            
            
            
            if (personel.Yetki == "A")
            {
                var kargolar = from x in c.KargoDetays select x;
                if (!string.IsNullOrEmpty(p))
                {
                     kargolar = kargolar.Where(y => y.TakipKodu.Contains(p));
                }
                return View(kargolar.ToList().ToPagedList(sayfa, 10));

            }
            else
            {
             var kargolar = from x in c.KargoDetays.Where(x => x.PersonelId == personel.PersonelId) select x; 
            
                if (!string.IsNullOrEmpty(p))
                {
                     kargolar = kargolar.Where(y => y.TakipKodu.Contains(p));
                }
                return View(kargolar.ToList().ToPagedList(sayfa, 10));
            }
          

        }

        [HttpGet]
        public ActionResult KargoEkle(int id)
        {
            TakipKodUret();
           

           var sorgu = c.SatisHarekets.Find(id);
            ViewBag.satisId = id;
            ViewBag.urunId = sorgu.Urun.UrunAd;
            ViewBag.cariId = sorgu.CariId;
            ViewBag.adres = sorgu.Cari.Adres;
            ViewBag.personelId = sorgu.PersonelId;

            ViewBag.cariAd = sorgu.Cari.CariAd + " " + sorgu.Cari.CariSoyad;
            ViewBag.personelAd = sorgu.Personel.PersonelAd + " " + sorgu.Personel.PersonelSoyad;
            return View();
        }
        [HttpPost]
        public ActionResult KargoEkle(KargoDetay kargoDetay)
        {
            kargoDetay.Tarih= DateTime.Parse(DateTime.Now.ToShortDateString());
            var sorgu = c.SatisHarekets.Find(kargoDetay.SatisId);
            kargoDetay.Durum = false;
            c.KargoDetays.Add(kargoDetay);
            sorgu.KargoDurum = true;
            c.SaveChanges();
            return RedirectToAction("Index");
        }
        

        public void TakipKodUret()
        {
            Random rdn = new Random();
            string[] karekterler = { "A", "B", "C", "D", "E", "K", "M", "Z" };
            int k1, k2, k3;
            k1 = rdn.Next(0, karekterler.Length);
            k2 = rdn.Next(0, karekterler.Length);
            k3 = rdn.Next(0, karekterler.Length);
            int s1, s2, s3;
            s1 = rdn.Next(100, 1000);
            s2 = rdn.Next(10, 99);
            s3 = rdn.Next(10, 99);

            string kod = s1.ToString() + karekterler[k1] + s2.ToString() + karekterler[k2] + s3.ToString() + karekterler[k3];
            ViewBag.takipKodu = kod;
        }
      
    }
}

MvcOnlineTicariOtomasyon/Views/Kargo/Index.cshtml
@using MvcOnlineTicariOtomasyon.Models.Siniflar
@using PagedList;
@using PagedList.Mvc;
@model PagedList.IPagedList<KargoDetay>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<br />
<h2>Kargolarım  </h2>
<hr />

@using (Html.BeginForm("Index", "Kargo", FormMethod.Get))
{
    <p>
        Kargo Takip Numarası: @Html.TextBox("p")
        <input type="submit" value="Ara" />
    </p>
}
<br />
<table class="table table-striped " style="margin-top:20px;">
    <tr>
        <th>Takip Kodu</th>
        <th>Personel</th>
        <th>Alıcı</th>
        <th>Tarih</th>
        <th>Adres</th>
        <th>Açıklama</th>
        <th>Kargo Durumu</th>
      

       

    </tr>
    @foreach (var d in Model)
    {
<tr>
    <td>@d.TakipKodu</td>
    <td>@d.Personel.PersonelAd @d.Personel.PersonelSoyad</td>
    <td>@d.Cari.CariAd @d.Cari.CariSoyad</td>

    <td>@d.Tarih.ToShortDateString()</td>
    <td>@d.Cari.Adres</td>
    <td>
      @d.Aciklama

        @*@if (@d.Aciklama.Length < 30)
        {
            @d.Aciklama
        }
        else
        {
            @d.Aciklama.Substring(0, 30).ToString()
        }*@



    </td>
    @if (d.Durum)
    {
        <td><a href="" class="btn btn-success">Teslim Edildi</a></td>
    }
    else
    {
        <td><a href="" class="btn btn-primary">Daha yolda</a></td>

    }
    


</tr>
    }

</table>
@Html.PagedListPager((IPagedList)Model, sayfa => Url.Action("Index", new { sayfa }))
 

MvcOnlineTicariOtomasyon/Views/Kargo/KargoEkle.cshtml
@model MvcOnlineTicariOtomasyon.Models.Siniflar.KargoDetay
@{
    ViewBag.Title = "KargoEkle";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<br />
<h2>Kargo Ekle</h2>
<hr />

<form class="form-group" method="post">
    @Html.Label("Takip Kodu ")
    <input type="text" name="TakipKodu" value="@ViewBag.takipKodu" class="form-control" readonly="readonly" />
    <br />
    @Html.Label("Şatış Kodu ")
    <input type="text" name="SatisId" value="@ViewBag.satisId" class="form-control" readonly="readonly" />
    <br />
    @Html.Label("Ürün")
    <input type="text" name="UrunId" value="@ViewBag.urunId" class="form-control" readonly="readonly" />

    <br />
    @Html.Label("Cari ")
    <input hidden type="text" name="CariId" value="@ViewBag.cariId" class="form-control" readonly="readonly" />
    <input type="text" name="CariId" value="@ViewBag.cariAd" class="form-control" readonly="readonly" />
    <br />
    @*@Html.Label("Adres ")
        <input type="text" name="Cari.Adres" value="@ViewBag.adres" class="form-control" readonly="readonly" />
        <br />*@
    @Html.Label("Gönderen Personel  ")
    <input hidden type="text" name="PersonelId" value="@ViewBag.personelId" class="form-control" readonly="readonly" />
    <input type="text" name="PersonelId" value="@ViewBag.personelAd" class="form-control" readonly="readonly" />
    <br />

    @Html.Label("Açıklama ")
    @Html.TextAreaFor(x => x.Aciklama, new { @class = "form-control" })
    <br />




    <button class="btn btn-info">Kaydet</button>
</form>